export interface CatalogProblemItem {
  title: string;
  description: string;
  minPrice: number;
  maxPrice: number;
}

export interface CatalogCategoryItem {
  name: string;
  slug: string;
  icon: string;
  filter: 'repairs' | 'appliances' | 'cleaning' | 'automotive' | 'tech' | 'interiors' | string;
  description: string;
  problems: CatalogProblemItem[];
}

const generalProblem = (categoryName: string): CatalogProblemItem => ({
  title: 'General Inspection & Diagnosis (Not Sure of the Problem)',
  description: `Professional visits on-site to inspect, diagnose any ${categoryName} issue, and provide an accurate upfront quote before starting work.`,
  minPrice: 149,
  maxPrice: 399,
});

export const ALL_50_CATEGORIES: CatalogCategoryItem[] = [
  {
    name: 'AC Repair & Service',
    slug: 'ac-repair',
    icon: 'ac_repair',
    filter: 'appliances',
    description: 'AC installation, repair, servicing, gas refilling, and maintenance.',
    problems: [
      { title: 'AC not cooling', description: 'AC is running but not blowing cold air', minPrice: 399, maxPrice: 899 },
      { title: 'AC leaking water', description: 'Water dropping or overflowing from indoor unit', minPrice: 299, maxPrice: 599 },
      { title: 'AC making loud noise', description: 'Vibration or grinding sound during operation', minPrice: 299, maxPrice: 699 },
      { title: 'AC not turning on', description: 'Complete power failure or remote control not responding', minPrice: 199, maxPrice: 499 },
      { title: 'AC installation / uninstallation', description: 'New AC mount or shifting existing AC unit', minPrice: 799, maxPrice: 1599 },
      { title: 'Gas refill & deep foam wash', description: 'Freon gas top-up and deep coil foam wash', minPrice: 1299, maxPrice: 2499 },
      generalProblem('AC Repair'),
    ],
  },
  {
    name: 'Electrician',
    slug: 'electrician',
    icon: 'electrician',
    filter: 'repairs',
    description: 'Electrical installation, wiring, switch, socket, fan, and electrical repair services.',
    problems: [
      { title: 'Power failure / MCB tripping', description: 'Complete blackout or circuit breaker repeatedly tripping', minPrice: 249, maxPrice: 599 },
      { title: 'Fan repair / regulator replacement', description: 'Ceiling or exhaust fan motor issue or speed control fault', minPrice: 149, maxPrice: 349 },
      { title: 'Switch / Socket repair & replacement', description: 'Burnt socket or faulty modular switch', minPrice: 99, maxPrice: 299 },
      { title: 'Light / Chandelier / Inverter installation', description: 'Fitting ceiling lights, panel lights, or decorative chandeliers', minPrice: 199, maxPrice: 799 },
      { title: 'Short circuit & wiring repair', description: 'Internal concealed wiring diagnosis and cable replacement', minPrice: 399, maxPrice: 999 },
      generalProblem('Electrical'),
    ],
  },
  {
    name: 'Plumber',
    slug: 'plumber',
    icon: 'plumber',
    filter: 'repairs',
    description: 'Plumbing repair, pipe installation, leakage repair, and water connection services.',
    problems: [
      { title: 'Tap / Shower leakage', description: 'Dripping tap, shower valve replacement or spindle repair', minPrice: 149, maxPrice: 399 },
      { title: 'Drain / Sink / Basin blockage', description: 'Clogged kitchen sink, wash basin or bathroom drain trap', minPrice: 249, maxPrice: 599 },
      { title: 'Toilet / Flush tank repair', description: 'Cistern leakage, siphon replacement, or Western commode fix', minPrice: 299, maxPrice: 699 },
      { title: 'Water tank & motor pipeline repair', description: 'Overhead tank connector or water booster pump plumbing', minPrice: 499, maxPrice: 1299 },
      { title: 'Geyser pipeline & valve fitting', description: 'Inlet/outlet pipeline and safety valve installation', minPrice: 349, maxPrice: 649 },
      generalProblem('Plumbing'),
    ],
  },
  {
    name: 'Carpenter',
    slug: 'carpenter',
    icon: 'carpenter',
    filter: 'repairs',
    description: 'Furniture repair, woodwork, door, window, cabinet, and carpentry services.',
    problems: [
      { title: 'Door lock, handle & latch repair', description: 'Stuck main door lock, handle replacement or latch alignment', minPrice: 199, maxPrice: 499 },
      { title: 'Furniture assembly / dismantling', description: 'Bed, wardrobe, bookshelf flatpack assembly', minPrice: 399, maxPrice: 1199 },
      { title: 'Cabinet hinge & drawer channel fix', description: 'Hydraulic soft-close hinges or drawer telescopic channels', minPrice: 199, maxPrice: 449 },
      { title: 'Custom wooden shelving & repair', description: 'Wall shelf fixing, partition alignment, or wooden trim', minPrice: 299, maxPrice: 799 },
      generalProblem('Carpentry'),
    ],
  },
  {
    name: 'Painter',
    slug: 'painter',
    icon: 'painter',
    filter: 'repairs',
    description: 'Interior and exterior wall painting, touch-up, and repainting services.',
    problems: [
      { title: 'Waterproofing & damp wall repair', description: 'Seepage treatment and anti-fungal putty application', minPrice: 799, maxPrice: 2499 },
      { title: 'Single room repaint / touch-up', description: 'Touch up or complete 2-coat emulsion paint for 1 room', minPrice: 1499, maxPrice: 3999 },
      { title: 'Full home interior painting', description: 'Primer, putty, and premium emulsion for full apartment', minPrice: 5999, maxPrice: 19999 },
      { title: 'Wall texture / Accent wall', description: 'Designer metallic or textured feature wall finish', minPrice: 1999, maxPrice: 4999 },
      generalProblem('Painting'),
    ],
  },
  {
    name: 'Home Cleaning',
    slug: 'home-cleaning',
    icon: 'cleaning',
    filter: 'cleaning',
    description: 'Regular home cleaning, dusting, mopping, and household cleaning services.',
    problems: [
      { title: 'Regular 1BHK/2BHK house cleaning', description: 'Mopping, vacuuming, dusting, and trash clearing', minPrice: 999, maxPrice: 1999 },
      { title: 'Post-party / Move-in quick clean', description: 'Fast thorough surface cleaning and sanitization', minPrice: 1299, maxPrice: 2499 },
      generalProblem('Home Cleaning'),
    ],
  },
  {
    name: 'Deep Cleaning',
    slug: 'deep-cleaning',
    icon: 'deep_cleaning',
    filter: 'cleaning',
    description: 'Complete deep cleaning services for homes, apartments, and offices.',
    problems: [
      { title: 'Full home deep machine cleaning', description: 'Floor scrubbing, balcony, windows, doors, and cobweb removal', minPrice: 1999, maxPrice: 4999 },
      { title: 'Office / Commercial deep clean', description: 'Workstation, cabin, and carpet deep sanitization', minPrice: 2999, maxPrice: 7999 },
      generalProblem('Deep Cleaning'),
    ],
  },
  {
    name: 'Pest Control',
    slug: 'pest-control',
    icon: 'pest_control',
    filter: 'cleaning',
    description: 'Termite, cockroach, rodent, mosquito, and bed bug pest control treatments.',
    problems: [
      { title: 'Cockroach gel & spray treatment', description: 'Kitchen and bathroom odorless gel baiting', minPrice: 599, maxPrice: 1199 },
      { title: 'Termite inspection & drill treatment', description: 'Woodwork drill, fill, and seal barrier protection', minPrice: 1499, maxPrice: 4999 },
      { title: 'Bed bug heat & chemical treatment', description: '2-visit mattress, bed frame, and sofa treatment', minPrice: 999, maxPrice: 2499 },
      { title: 'Mosquito & Rodent control', description: 'Traps, rodent repellent paste, and indoor fogging', minPrice: 699, maxPrice: 1499 },
      generalProblem('Pest Control'),
    ],
  },
  {
    name: 'Washing Machine Repair',
    slug: 'washing-machine-repair',
    icon: 'washing_machine',
    filter: 'appliances',
    description: 'Washing machine inspection, repair, installation, and maintenance.',
    problems: [
      { title: 'Washing machine not spinning / drum stuck', description: 'Drum belt, motor, or bearing fault', minPrice: 349, maxPrice: 999 },
      { title: 'Water not draining / inlet issue', description: 'Drain pump blockage, inlet valve, or filter cleaning', minPrice: 299, maxPrice: 699 },
      { title: 'Vibration / loud noise during spin', description: 'Suspension rod shock absorbers or balancing fault', minPrice: 349, maxPrice: 899 },
      { title: 'PCB / Power issue', description: 'Control board power supply or error code diagnostics', minPrice: 499, maxPrice: 1499 },
      generalProblem('Washing Machine'),
    ],
  },
  {
    name: 'Refrigerator Repair',
    slug: 'refrigerator-repair',
    icon: 'refrigerator',
    filter: 'appliances',
    description: 'Refrigerator repair, cooling issues, gas filling, and maintenance services.',
    problems: [
      { title: 'Fridge not cooling / compressor not starting', description: 'Thermostat, relay, or compressor issue', minPrice: 399, maxPrice: 1199 },
      { title: 'Excess ice buildup / defrost fault', description: 'Defrost timer, bimetal sensor, or heater repair', minPrice: 349, maxPrice: 899 },
      { title: 'Water leakage inside / underneath', description: 'Drain tube unclogging and drip pan realignment', minPrice: 249, maxPrice: 549 },
      { title: 'Gas leakage & refill', description: 'Leak brazing, vacuuming, and refrigerant charging', minPrice: 1299, maxPrice: 2499 },
      generalProblem('Refrigerator'),
    ],
  },
  {
    name: 'Microwave Repair',
    slug: 'microwave-repair',
    icon: 'microwave',
    filter: 'appliances',
    description: 'Microwave oven inspection, repair, and maintenance services.',
    problems: [
      { title: 'Microwave not heating food', description: 'Magnetron, high voltage capacitor, or diode repair', minPrice: 349, maxPrice: 899 },
      { title: 'Turntable plate not rotating', description: 'Coupler or turntable motor replacement', minPrice: 249, maxPrice: 549 },
      { title: 'Touch panel / buttons not responding', description: 'Membrane keypad or control board repair', minPrice: 399, maxPrice: 999 },
      { title: 'Sparking inside chamber', description: 'Waveguide mica cover replacement', minPrice: 249, maxPrice: 499 },
      generalProblem('Microwave'),
    ],
  },
  {
    name: 'TV Repair',
    slug: 'tv-repair',
    icon: 'tv',
    filter: 'appliances',
    description: 'LED, LCD, Smart TV installation, troubleshooting, and repair services.',
    problems: [
      { title: 'Sound working but no display / black screen', description: 'LED backlight strip or T-Con board issue', minPrice: 499, maxPrice: 1999 },
      { title: 'TV not turning on / red light blinking', description: 'Power supply motherboard diagnosis', minPrice: 399, maxPrice: 1299 },
      { title: 'HDMI / Wi-Fi / Speaker issue', description: 'Port replacement or audio IC repair', minPrice: 299, maxPrice: 799 },
      generalProblem('TV Repair'),
    ],
  },
  {
    name: 'RO & Water Purifier Service',
    slug: 'ro-service',
    icon: 'water_purifier',
    filter: 'appliances',
    description: 'RO installation, filter replacement, servicing, and water purifier repair.',
    problems: [
      { title: 'Filter replacement & complete service', description: 'Sediment, pre-carbon, and post-carbon filter replacement', minPrice: 399, maxPrice: 1499 },
      { title: 'Water taste / bad odor issue', description: 'Mineral cartridge and carbon polishing service', minPrice: 299, maxPrice: 699 },
      { title: 'Water leakage from body or pump', description: 'Elbow connectors, membrane housing, or solenoid valve fix', minPrice: 249, maxPrice: 549 },
      { title: 'RO booster pump not running / low pressure', description: 'SMPS adapter or booster pump repair', minPrice: 399, maxPrice: 1299 },
      generalProblem('RO Water Purifier'),
    ],
  },
  {
    name: 'Geyser Repair',
    slug: 'geyser-repair',
    icon: 'geyser',
    filter: 'appliances',
    description: 'Geyser installation, repair, heating element replacement, and servicing.',
    problems: [
      { title: 'Water not heating / takes too long', description: 'Heating element or thermostat replacement', minPrice: 349, maxPrice: 899 },
      { title: 'Water leaking from tank / valve', description: 'Safety pressure valve or gasket leak fix', minPrice: 299, maxPrice: 649 },
      { title: 'Geyser tripping MCB / electric shock', description: 'Element earthing fault or short circuit repair', minPrice: 349, maxPrice: 799 },
      { title: 'New geyser installation / removal', description: 'Wall mounting and inlet/outlet connection', minPrice: 399, maxPrice: 699 },
      generalProblem('Geyser'),
    ],
  },
  {
    name: 'Chimney Repair & Service',
    slug: 'chimney-service',
    icon: 'chimney',
    filter: 'appliances',
    description: 'Kitchen chimney cleaning, repair, installation, and maintenance services.',
    problems: [
      { title: 'Deep degreasing & filter cleaning', description: 'Baffle/mesh filter foam wash and oil collector clearing', minPrice: 499, maxPrice: 999 },
      { title: 'Low suction power / motor noise', description: 'Blower fan repair or duct unclogging', minPrice: 349, maxPrice: 849 },
      { title: 'Touch / Gesture control not working', description: 'Sensor PCB board repair or touch panel replacement', minPrice: 399, maxPrice: 999 },
      generalProblem('Chimney'),
    ],
  },
  {
    name: 'Gas Stove Repair',
    slug: 'gas-stove-repair',
    icon: 'gas_stove',
    filter: 'appliances',
    description: 'Gas stove inspection, burner repair, ignition repair, and servicing.',
    problems: [
      { title: 'Burner flame low / yellow flame', description: 'Jet nozzle unclogging and air mix tuning', minPrice: 199, maxPrice: 399 },
      { title: 'Gas leakage / knob loose', description: 'Valve spindle greasing or gas pipe replacement', minPrice: 199, maxPrice: 449 },
      { title: 'Auto-ignition not sparking', description: 'Spark generator or switch replacement', minPrice: 249, maxPrice: 599 },
      generalProblem('Gas Stove'),
    ],
  },
  {
    name: 'Locksmith',
    slug: 'locksmith',
    icon: 'locksmith',
    filter: 'repairs',
    description: 'Lock repair, replacement, key duplication, and emergency locksmith services.',
    problems: [
      { title: 'Emergency door lockout / lock opening', description: 'Non-destructive opening of jammed or locked door', minPrice: 349, maxPrice: 799 },
      { title: 'Main door lock replacement & fitting', description: 'Installation of high-security mortise or rim lock', minPrice: 299, maxPrice: 699 },
      { title: 'Cabinet / drawer lock repair', description: 'Key extraction and cylinder replacement', minPrice: 199, maxPrice: 399 },
      generalProblem('Locksmith'),
    ],
  },
  {
    name: 'CCTV Installation',
    slug: 'cctv-installation',
    icon: 'cctv',
    filter: 'tech',
    description: 'CCTV camera installation, configuration, maintenance, and repair.',
    problems: [
      { title: 'New CCTV camera installation & wiring', description: 'Dome/Bullet IP or HD camera mounting and DVR cabling', minPrice: 499, maxPrice: 1999 },
      { title: 'Camera offline / no video on mobile app', description: 'DVR network setup, port forwarding, or power adapter fix', minPrice: 349, maxPrice: 799 },
      { title: 'Hard drive not recording / night vision issue', description: 'HDD storage formatting or IR LED replacement', minPrice: 299, maxPrice: 649 },
      generalProblem('CCTV'),
    ],
  },
  {
    name: 'Wi-Fi & Router Service',
    slug: 'wifi-router',
    icon: 'wifi',
    filter: 'tech',
    description: 'Wi-Fi setup, router installation, network troubleshooting, and configuration.',
    problems: [
      { title: 'Wi-Fi router setup & mesh configuration', description: 'Router installation, SSID security, and range extender setup', minPrice: 299, maxPrice: 699 },
      { title: 'Slow internet / frequent disconnection', description: 'LAN cable crimping, DNS optimization, and channel tuning', minPrice: 249, maxPrice: 549 },
      generalProblem('Wi-Fi & Router'),
    ],
  },
  {
    name: 'Computer Repair',
    slug: 'computer-repair',
    icon: 'computer',
    filter: 'tech',
    description: 'Desktop and laptop repair, software installation, troubleshooting, and maintenance.',
    problems: [
      { title: 'Laptop screen / display issue', description: 'Broken screen replacement or flickering backlight', minPrice: 499, maxPrice: 2499 },
      { title: 'Battery & charging issue', description: 'Battery not charging or DC power jack repair', minPrice: 349, maxPrice: 1299 },
      { title: 'Slow performance / SSD & RAM upgrade', description: 'NVMe SSD installation and speed optimization', minPrice: 399, maxPrice: 1499 },
      { title: 'Windows / macOS reinstall & virus removal', description: 'Clean OS install, driver setup, and antivirus scan', minPrice: 399, maxPrice: 799 },
      generalProblem('Computer'),
    ],
  },
  {
    name: 'Mobile Phone Repair',
    slug: 'mobile-repair',
    icon: 'mobile_repair',
    filter: 'tech',
    description: 'Smartphone screen, battery, charging, software, and hardware repair.',
    problems: [
      { title: 'Cracked screen / display replacement', description: 'Touchscreen digitizer and LCD/AMOLED panel repair', minPrice: 499, maxPrice: 3499 },
      { title: 'Battery draining fast / swelling', description: 'OEM replacement battery fitting', minPrice: 399, maxPrice: 1499 },
      { title: 'Charging port / speaker / mic repair', description: 'Type-C/Lightning connector or earpiece fix', minPrice: 299, maxPrice: 799 },
      generalProblem('Mobile Phone'),
    ],
  },
  {
    name: 'Home Appliance Repair',
    slug: 'home-appliance-repair',
    icon: 'home_appliance',
    filter: 'appliances',
    description: 'Repair and maintenance services for common household appliances.',
    problems: [
      { title: 'Mixer grinder / blender motor issue', description: 'Coupler, carbon brush, or jar blade replacement', minPrice: 199, maxPrice: 449 },
      { title: 'Induction cooktop not heating', description: 'IGBT circuit, coil, or cooling fan repair', minPrice: 299, maxPrice: 699 },
      { title: 'Iron / Vacuum cleaner repair', description: 'Thermostat, thermal fuse, or power cord fix', minPrice: 199, maxPrice: 499 },
      generalProblem('Home Appliance'),
    ],
  },
  {
    name: 'Bathroom Cleaning',
    slug: 'bathroom-cleaning',
    icon: 'bathroom_cleaning',
    filter: 'cleaning',
    description: 'Professional bathroom cleaning, sanitization, and stain removal.',
    problems: [
      { title: 'Hard water scale & tile stain removal', description: 'Chemical descaling of wall tiles, taps, and mirror', minPrice: 399, maxPrice: 799 },
      { title: 'Complete bathroom deep disinfection', description: 'Floor scrubbing, commode sanitization, and drain clearing', minPrice: 499, maxPrice: 999 },
      generalProblem('Bathroom Cleaning'),
    ],
  },
  {
    name: 'Kitchen Cleaning',
    slug: 'kitchen-cleaning',
    icon: 'kitchen_cleaning',
    filter: 'cleaning',
    description: 'Kitchen cleaning including cabinets, tiles, countertops, and appliances.',
    problems: [
      { title: 'Countertop, tile & stove degreasing', description: 'Removal of sticky grease, oil film, and grime', minPrice: 499, maxPrice: 999 },
      { title: 'Full kitchen deep clean (inside cabinets)', description: 'Cabinet interior wipe-down, exhaust fan, and sink descaling', minPrice: 799, maxPrice: 1499 },
      generalProblem('Kitchen Cleaning'),
    ],
  },
  {
    name: 'Sofa Cleaning',
    slug: 'sofa-cleaning',
    icon: 'sofa',
    filter: 'cleaning',
    description: 'Professional sofa and upholstery cleaning for fabric and leather furniture.',
    problems: [
      { title: 'Fabric sofa wet shampoo & vacuum extraction', description: 'Stain treatment, foam shampoo, and moisture suction (per seat)', minPrice: 399, maxPrice: 1299 },
      { title: 'Leather sofa conditioning & polish', description: 'Leather foam cleaner and moisturizing protective cream', minPrice: 499, maxPrice: 1499 },
      generalProblem('Sofa Cleaning'),
    ],
  },
  {
    name: 'Carpet Cleaning',
    slug: 'carpet-cleaning',
    icon: 'carpet',
    filter: 'cleaning',
    description: 'Professional carpet washing, stain removal, and deep cleaning.',
    problems: [
      { title: 'Living room area rug deep wash', description: 'Deep fiber agitation, stain lift, and extraction', minPrice: 499, maxPrice: 1299 },
      { title: 'Wall-to-wall carpet machine shampooing', description: 'High-suction carpet machine scrubbing and deodorization', minPrice: 999, maxPrice: 2499 },
      generalProblem('Carpet Cleaning'),
    ],
  },
  {
    name: 'Mattress Cleaning',
    slug: 'mattress-cleaning',
    icon: 'mattress',
    filter: 'cleaning',
    description: 'Mattress deep cleaning, dust removal, stain treatment, and sanitization.',
    problems: [
      { title: 'Single / King mattress UV & extraction clean', description: 'Dust mite extraction, stain treatment, and anti-allergen spray', minPrice: 499, maxPrice: 1199 },
      generalProblem('Mattress Cleaning'),
    ],
  },
  {
    name: 'Water Tank Cleaning',
    slug: 'water-tank-cleaning',
    icon: 'water_tank',
    filter: 'cleaning',
    description: 'Professional overhead and underground water tank cleaning services.',
    problems: [
      { title: 'Overhead sintex tank cleaning (up to 1000L)', description: 'Sludge extraction, high-pressure wash, and UV disinfection', minPrice: 599, maxPrice: 1299 },
      { title: 'Underground sump cleaning (2000L - 5000L)', description: 'Dewatering, scrubbing, and antibacterial treatment', minPrice: 999, maxPrice: 2499 },
      generalProblem('Water Tank Cleaning'),
    ],
  },
  {
    name: 'Home Sanitization',
    slug: 'home-sanitization',
    icon: 'sanitization',
    filter: 'cleaning',
    description: 'Home and office sanitization and disinfection services.',
    problems: [
      { title: 'Full home anti-viral fogging treatment', description: 'Hospital-grade disinfectant mist for all rooms and surfaces', minPrice: 699, maxPrice: 1499 },
      generalProblem('Home Sanitization'),
    ],
  },
  {
    name: 'Floor Polishing',
    slug: 'floor-polishing',
    icon: 'floor_polishing',
    filter: 'interiors',
    description: 'Floor polishing, buffing, restoration, and maintenance services.',
    problems: [
      { title: 'Marble floor diamond grinding & polish', description: 'Multi-grit diamond pad grinding and crystallization shine', minPrice: 1999, maxPrice: 6999 },
      { title: 'Granite / Mosaic floor buffing & seal', description: 'Wax buffing and stain protection sealant', minPrice: 1499, maxPrice: 4999 },
      generalProblem('Floor Polishing'),
    ],
  },
  {
    name: 'Interior Painting',
    slug: 'interior-painting',
    icon: 'interior_painting',
    filter: 'interiors',
    description: 'Interior wall, ceiling, room, and decorative painting services.',
    problems: [
      { title: '1 Room / Accent wall repaint', description: '2 coats of premium interior emulsion with surface prep', minPrice: 1299, maxPrice: 3499 },
      { title: 'Full apartment interior painting', description: 'Wall putty, primer, and luxury smooth emulsion finish', minPrice: 4999, maxPrice: 18999 },
      generalProblem('Interior Painting'),
    ],
  },
  {
    name: 'Exterior Painting',
    slug: 'exterior-painting',
    icon: 'exterior_painting',
    filter: 'interiors',
    description: 'Exterior house, building, balcony, and boundary wall painting services.',
    problems: [
      { title: 'Balcony / Boundary wall exterior paint', description: 'Weatherproof anti-algae silicone paint coating', minPrice: 1499, maxPrice: 4999 },
      { title: 'Full house exterior weather shield', description: 'Pressure wash prep, crack seal, and exterior acrylic paint', minPrice: 7999, maxPrice: 29999 },
      generalProblem('Exterior Painting'),
    ],
  },
  {
    name: 'Modular Kitchen Service',
    slug: 'modular-kitchen',
    icon: 'kitchen',
    filter: 'interiors',
    description: 'Modular kitchen installation, repair, modification, and maintenance.',
    problems: [
      { title: 'Drawer basket & telescopic channel fix', description: 'Tandem box realignment or soft-close runner replacement', minPrice: 299, maxPrice: 699 },
      { title: 'Cabinet shutter hinge & hydraulic lift repair', description: 'Gas strut replacement or hydraulic hinge adjustment', minPrice: 249, maxPrice: 549 },
      { title: 'New modular cabinet addition / customization', description: 'Plywood woodwork, acrylic sheet lamination, and fitting', minPrice: 999, maxPrice: 3499 },
      generalProblem('Modular Kitchen'),
    ],
  },
  {
    name: 'Furniture Assembly',
    slug: 'furniture-assembly',
    icon: 'furniture',
    filter: 'interiors',
    description: 'Professional assembly and installation of beds, tables, wardrobes, and other furniture.',
    problems: [
      { title: 'Bed assembly (Single / Queen / King with hydraulic)', description: 'Flatpack frame, headboard, and hydraulic lift assembly', minPrice: 399, maxPrice: 999 },
      { title: 'Wardrobe / Almirah flatpack assembly', description: '2-door / 3-door / 4-door wardrobe construction', minPrice: 499, maxPrice: 1499 },
      { title: 'Office table, chair & bookshelf assembly', description: 'Desk setup and ergonomic chair fitting', minPrice: 299, maxPrice: 699 },
      generalProblem('Furniture Assembly'),
    ],
  },
  {
    name: 'Furniture Repair',
    slug: 'furniture-repair',
    icon: 'furniture_repair',
    filter: 'interiors',
    description: 'Repair and restoration of wooden and household furniture.',
    problems: [
      { title: 'Broken chair / table leg repair', description: 'Wood joining, dowel reinforcement, and gluing', minPrice: 199, maxPrice: 499 },
      { title: 'Bed plank / frame creak fix', description: 'Structural support slat replacement and tightening', minPrice: 249, maxPrice: 599 },
      { title: 'Wood re-polishing & scratch touch-up', description: 'PU / Melamine wood polish touch up', minPrice: 499, maxPrice: 1299 },
      generalProblem('Furniture Repair'),
    ],
  },
  {
    name: 'Curtain Installation',
    slug: 'curtain-installation',
    icon: 'curtain',
    filter: 'interiors',
    description: 'Curtain rod, blinds, curtain, and window covering installation.',
    problems: [
      { title: 'Curtain rod / bracket drill & mount', description: 'Precision wall drilling and rod fitting (per window)', minPrice: 149, maxPrice: 299 },
      { title: 'Roller / Zebra / Venetian blinds installation', description: 'Window blind mechanism mounting and alignment', minPrice: 199, maxPrice: 449 },
      generalProblem('Curtain Installation'),
    ],
  },
  {
    name: 'TV Wall Mounting',
    slug: 'tv-wall-mounting',
    icon: 'tv_mount',
    filter: 'interiors',
    description: 'Professional TV wall mounting, bracket installation, and setup.',
    problems: [
      { title: 'Standard fixed wall mount (32" - 55")', description: 'Wall drill, bracket fixing, and cable management', minPrice: 299, maxPrice: 499 },
      { title: 'Swivel / Tilt / Full motion bracket mount', description: 'Articulated arm bracket mounting for large TVs', minPrice: 399, maxPrice: 699 },
      generalProblem('TV Wall Mounting'),
    ],
  },
  {
    name: 'Appliance Installation',
    slug: 'appliance-installation',
    icon: 'installation',
    filter: 'appliances',
    description: 'Installation and setup of home appliances by trained professionals.',
    problems: [
      { title: 'Washing machine / Dishwasher installation', description: 'Inlet hose, drain connector, and electrical setup', minPrice: 249, maxPrice: 499 },
      { title: 'Microwave / OTG wall bracket installation', description: 'Heavy-duty wall bracket mounting', minPrice: 199, maxPrice: 399 },
      generalProblem('Appliance Installation'),
    ],
  },
  {
    name: 'Bathroom Repair',
    slug: 'bathroom-repair',
    icon: 'bathroom',
    filter: 'repairs',
    description: 'Bathroom plumbing, fixtures, fittings, leakage, and repair services.',
    problems: [
      { title: 'Towel rod, mirror, shelf & accessory fitting', description: 'Tile drill and accessory mounting', minPrice: 149, maxPrice: 349 },
      { title: 'Shower mixer / Diverter cartridge repair', description: 'Thermostatic or single lever diverter cartridge replacement', minPrice: 349, maxPrice: 799 },
      generalProblem('Bathroom Repair'),
    ],
  },
  {
    name: 'Kitchen Repair',
    slug: 'kitchen-repair',
    icon: 'kitchen_repair',
    filter: 'repairs',
    description: 'Kitchen plumbing, cabinets, fittings, fixtures, and repair services.',
    problems: [
      { title: 'Kitchen sink faucet replacement / leak fix', description: 'Swan neck or pull-out faucet installation', minPrice: 199, maxPrice: 449 },
      { title: 'Sink waste coupling & drainage pipe fix', description: 'Coupling replacement and PVC drain pipe sealing', minPrice: 199, maxPrice: 399 },
      generalProblem('Kitchen Repair'),
    ],
  },
  {
    name: 'Drainage & Sewer Service',
    slug: 'drainage-sewer',
    icon: 'drainage',
    filter: 'repairs',
    description: 'Drain cleaning, blockage removal, sewer maintenance, and drainage repair.',
    problems: [
      { title: 'Severely clogged main sewer line clearing', description: 'Electric rodder snake machine clearing', minPrice: 499, maxPrice: 1299 },
      { title: 'Bathroom floor gully trap de-clogging', description: 'Debris, hair, and soap scum blockage removal', minPrice: 249, maxPrice: 499 },
      generalProblem('Drainage & Sewer'),
    ],
  },
  {
    name: 'Water Leakage Repair',
    slug: 'water-leakage',
    icon: 'water_leakage',
    filter: 'repairs',
    description: 'Detection and repair of water leakage in pipes, walls, bathrooms, and roofs.',
    problems: [
      { title: 'Concealed pipe leak detection & fix', description: 'Pressure test leak tracing and localized wall repair', minPrice: 499, maxPrice: 1499 },
      { title: 'Ceiling / Wall seepage repair', description: 'Epoxy injection and waterproof barrier putty', minPrice: 799, maxPrice: 2499 },
      generalProblem('Water Leakage'),
    ],
  },
  {
    name: 'Waterproofing',
    slug: 'waterproofing',
    icon: 'waterproofing',
    filter: 'interiors',
    description: 'Roof, bathroom, terrace, balcony, and wall waterproofing services.',
    problems: [
      { title: 'Terrace & roof elastomeric waterproofing', description: 'Fibre mesh and polymer-modified acrylic liquid membrane', minPrice: 2499, maxPrice: 9999 },
      { title: 'Bathroom tile joint epoxy regrouting', description: 'Waterproof epoxy grout seal preventing seepage into lower floors', minPrice: 699, maxPrice: 1899 },
      generalProblem('Waterproofing'),
    ],
  },
  {
    name: 'False Ceiling',
    slug: 'false-ceiling',
    icon: 'false_ceiling',
    filter: 'interiors',
    description: 'False ceiling installation, repair, modification, and maintenance.',
    problems: [
      { title: 'Gypsum / POP false ceiling patch repair', description: 'Water damaged board replacement and joint tape finish', minPrice: 499, maxPrice: 1299 },
      { title: 'Cove light & ceiling panel cutting', description: 'Spotlight hole cutting and framing adjustment', minPrice: 299, maxPrice: 699 },
      generalProblem('False Ceiling'),
    ],
  },
  {
    name: 'Tile Installation & Repair',
    slug: 'tile-service',
    icon: 'tiles',
    filter: 'interiors',
    description: 'Floor and wall tile installation, replacement, repair, and grouting.',
    problems: [
      { title: 'Broken / Hollow tile replacement', description: 'Removal of cracked tile and adhesive re-fixing', minPrice: 349, maxPrice: 799 },
      { title: 'Complete room tile regrouting & cleaning', description: 'Cement/epoxy grout refresh', minPrice: 499, maxPrice: 1299 },
      generalProblem('Tile Service'),
    ],
  },
  {
    name: 'Packers & Movers',
    slug: 'packers-movers',
    icon: 'moving',
    filter: 'automotive',
    description: 'Home shifting, office relocation, packing, loading, transportation, and unloading.',
    problems: [
      { title: 'Local 1BHK/2BHK home shifting inspection', description: 'On-site volume evaluation, bubble wrap packing, and truck transport', minPrice: 2999, maxPrice: 11999 },
      { title: 'Single item / Few furniture moving', description: 'Pickup and drop of sofa, bed, or fridge', minPrice: 999, maxPrice: 2999 },
      generalProblem('Packers & Movers'),
    ],
  },
  {
    name: 'Driver on Demand',
    slug: 'driver-on-demand',
    icon: 'driver',
    filter: 'automotive',
    description: 'Professional drivers available for personal, local, and outstation requirements.',
    problems: [
      { title: 'Hourly in-city personal driver (4 hrs / 8 hrs)', description: 'Verified professional driver for manual or automatic cars', minPrice: 399, maxPrice: 899 },
      { title: 'Outstation one-way / round trip driver', description: 'Experienced highway driver', minPrice: 999, maxPrice: 2499 },
      generalProblem('Driver Service'),
    ],
  },
  {
    name: 'Car Washing & Detailing',
    slug: 'car-wash-detailing',
    icon: 'car_wash',
    filter: 'automotive',
    description: 'Car washing, interior cleaning, polishing, and professional detailing.',
    problems: [
      { title: 'Doorstep waterless wash & interior vacuum', description: 'Foam wash, tire dressing, dashboard polish, and vacuuming', minPrice: 399, maxPrice: 799 },
      { title: 'Full car interior deep shampoo & steam clean', description: 'Upholstery wet extraction, roof lining, and AC vent disinfection', minPrice: 899, maxPrice: 1999 },
      generalProblem('Car Detailing'),
    ],
  },
  {
    name: 'Bike Repair & Service',
    slug: 'bike-repair',
    icon: 'bike_repair',
    filter: 'automotive',
    description: 'Two-wheeler servicing, repair, maintenance, and roadside assistance.',
    problems: [
      { title: 'Doorstep bike general service', description: 'Engine oil change, brake tuning, chain lubrication, and spark plug clean', minPrice: 349, maxPrice: 699 },
      { title: 'Bike not starting / battery & electrical issue', description: 'Self-starter, battery jump start, or carburetor clean', minPrice: 199, maxPrice: 499 },
      { title: 'Puncture / tyre change & brake pad replacement', description: 'Tubeless tyre puncture repair and drum/disc brake pad fitting', minPrice: 149, maxPrice: 399 },
      generalProblem('Bike Repair'),
    ],
  },
  {
    name: 'Smart Home & Security',
    slug: 'smart-home-security',
    icon: 'smart_home',
    filter: 'tech',
    description: 'Smart home device installation, security systems, sensors, and automation.',
    problems: [
      { title: 'Smart digital door lock installation', description: 'Fingerprint, PIN, and RFID smart lock fitting and setup', minPrice: 599, maxPrice: 1299 },
      { title: 'Smart Wi-Fi video doorbell & chime setup', description: 'Mounting and smartphone pairing with two-way audio', minPrice: 349, maxPrice: 699 },
      { title: 'Smart lighting / touch switch automation setup', description: 'Smart switch module wiring and Alexa/Google Home voice pairing', minPrice: 399, maxPrice: 999 },
      generalProblem('Smart Home'),
    ],
  },
];
